### ISSUE TITLE
[Bug] Some images get uploaded sideways

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#108]
Some images are uploaded sideways

**Comment by olsen-adam** [comment]
Unable to re-create after various testing

**Comment by natewu** [comment]
@olsen-adam ![Screenshot_20240406-022149_NoStack.png](https://github.com/CMPUT301W24T27/NoStack/assets/36091727/a36d9c42-2aee-41b0-af46-a29d5a3f89ad)

![IMG_20231009_223159_01.jpg](https://github.com/CMPUT301W24T27/NoStack/assets/36091727/26c0ceef-f3e8-449f-b3ae-1b1d94399ddb)

this image as an example...

**Comment by olsen-adam** [comment]
could not replicate this bug 🤷‍♂
