### ISSUE TITLE
[Bug] After clicking on any admin popup, cannot click from other panel

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#127]
Ex. Clicking on an image from admin panel does not let user click on profile or event.
Or clicking on profile then changing to images will allow both popups but going back to profile cannot click on profile.

Happens on all panels

**Comment by natewu** [comment]
Update, if you scroll on the view first then click on an item it will work.

**Comment by olsen-adam** [comment]
Could not replicate. It should be fixed with the nav bar now?

**Comment by natewu** [comment]
@olsen-adam this is solved when i switched to recycler views
