### ISSUE TITLE
[Bug] If image is larger than certain size, exceed buffer error

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#128]
On firebase storage, if you have an image that is too big in size, it will prevent the application from loading the image.

This shouldn't be an issue since we compress images now, but in the case that a user compresses an image and its still too big, is worth looking into.

Testing:
- Upload a large image directly from firebase storage for no compression
- Test in app
- Look in logcat for the buffer error

**Comment by olsen-adam** [comment]
#137 #135
