### ISSUE TITLE
US 02.02.03 - Update profile information

### ISSUE THREAD

**Issue by olsen-adam** [CMPUT301W24T27/NoStack#23]
## Issue Description

 As an attendee, I want to update information such as name, homepage, and contact information on my profile.

## Acceptance Criteria
 
- [ ] Editable fields in profile when edit button clicked.
- [ ] After saving, fields should be updated in the database
- [ ] Fields should be updated in profile

## Unknowns

- Edit this section with any unknowns about how we will do particulars

**Comment by natewu** [comment]
Same branch as #25
