### ISSUE TITLE
US 02.02.01 - Attendee can set profile photo

### ISSUE THREAD

**Issue by olsen-adam** [CMPUT301W24T27/NoStack#25]
## Issue Description

As an attendee, I want to upload a profile picture for a more personalized experience.

## Acceptance Criteria
 
- [ ] User can set their profile photo.

## Unknowns

- Edit this section with any unknowns about how we will do particulars

**Comment by natewu** [comment]
above two have similar functionality can be combined into same branch
since developing this feature would rely on the other two
