### ISSUE TITLE
US 01.03.01 - Organizer send notifications

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#8]
## Issue Description

 As an organizer, I want to send notifications to all attendees through the app.

## Acceptance Criteria
 
- [ ] Create a notification with a message
- [ ] Set a time to send this notification / send immediately

## Unknowns

- Edit this section with any unknowns about how we will do particulars

**Comment by olsen-adam** [comment]
Closed as per #155
