### ISSUE TITLE
[Bug] If user opened an event then goes back and tries to set their profile picture, app crash

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#80]
App crashes when user opens an event then goes back and tries to set their profile picture(have not confirmed if all events or event only where the user created themselves).

Also probably due to nav graph popping the previous screen off to the event itself, a bandaid fix is to not pop off the stack and go back to the organizer/attendee home only when clicking the back button/android back button

**Comment by olsen-adam** [comment]
Could not replicate this bug on my computer @natewu

**Comment by natewu** [comment]
@olsen-adam let's push this to backlog since I can't get it to replicate on my computer either, only happened on phone

**Comment by olsen-adam** [comment]
👍🏼

**Comment by natewu** [comment]
@olsen-adam seems to be fixed either due to the previous navgraph update  or the navbar update

**Comment by natewu** [comment]
close issue for now as its not appearing on my physical device
