### ISSUE TITLE
[Bug] If user was in a fragment, exits, re-enters, user information is forgotten

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#81]
If user initially is signed in then goes to either home fragment, then leave the app(android will hibernate the app). Then when they open again they enter the fragment without any user information persisted.

![Image](https://github.com/CMPUT301W24T27/NoStack/assets/36091727/0b4db711-94b5-4bf4-9232-317f68dd314f)

**Comment by olsen-adam** [comment]
I think we fixed this bug by switching to the view model. One more person check but I think this one has been fixed
